/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BulkUpdateManager: typeof import('./src/components/update/BulkUpdateManager.vue')['default']
    ConfigForm: typeof import('./src/components/settings/forms/ConfigForm.vue')['default']
    ContainerCard: typeof import('./src/components/container/ContainerCard.vue')['default']
    ContainerForm: typeof import('./src/components/container/ContainerForm.vue')['default']
    ContainerStats: typeof import('./src/components/dashboard/widgets/ContainerStats.vue')['default']
    CronEditor: typeof import('./src/components/settings/forms/CronEditor.vue')['default']
    DockerConfig: typeof import('./src/components/settings/DockerConfig.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FileUpload: typeof import('./src/components/settings/forms/FileUpload.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HealthMonitor: typeof import('./src/components/dashboard/widgets/HealthMonitor.vue')['default']
    KeyValueEditor: typeof import('./src/components/settings/forms/KeyValueEditor.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LogViewer: typeof import('./src/components/container/LogViewer.vue')['default']
    MonitoringConfig: typeof import('./src/components/settings/MonitoringConfig.vue')['default']
    NotificationCenter: typeof import('./src/components/dashboard/widgets/NotificationCenter.vue')['default']
    NotificationConfig: typeof import('./src/components/settings/NotificationConfig.vue')['default']
    PasswordField: typeof import('./src/components/settings/forms/PasswordField.vue')['default']
    QuickActions: typeof import('./src/components/dashboard/widgets/QuickActions.vue')['default']
    RealtimeMonitor: typeof import('./src/components/dashboard/widgets/RealtimeMonitor.vue')['default']
    RecentActivities: typeof import('./src/components/dashboard/widgets/RecentActivities.vue')['default']
    RegistryConfig: typeof import('./src/components/settings/RegistryConfig.vue')['default']
    ResourceCharts: typeof import('./src/components/dashboard/widgets/ResourceCharts.vue')['default']
    ResourceMonitor: typeof import('./src/components/container/ResourceMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulerConfig: typeof import('./src/components/settings/SchedulerConfig.vue')['default']
    SecurityConfig: typeof import('./src/components/settings/SecurityConfig.vue')['default']
    SecurityDashboard: typeof import('./src/components/dashboard/widgets/SecurityDashboard.vue')['default']
    SettingsDrawer: typeof import('./src/components/SettingsDrawer.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SystemConfig: typeof import('./src/components/settings/SystemConfig.vue')['default']
    SystemOverview: typeof import('./src/components/dashboard/widgets/SystemOverview.vue')['default']
    UpdateActivity: typeof import('./src/components/dashboard/widgets/UpdateActivity.vue')['default']
    UpdateCard: typeof import('./src/components/update/UpdateCard.vue')['default']
    UpdateDetailsViewer: typeof import('./src/components/update/UpdateDetailsViewer.vue')['default']
    UpdateHistoryItem: typeof import('./src/components/update/UpdateHistoryItem.vue')['default']
    UpdateLogsViewer: typeof import('./src/components/update/UpdateLogsViewer.vue')['default']
    UpdateManager: typeof import('./src/components/container/UpdateManager.vue')['default']
    UpdatePolicies: typeof import('./src/components/settings/UpdatePolicies.vue')['default']
    UpdateProgress: typeof import('./src/components/update/UpdateProgress.vue')['default']
    UpdateScheduler: typeof import('./src/components/update/UpdateScheduler.vue')['default']
    UserManagement: typeof import('./src/components/settings/UserManagement.vue')['default']
    VersionComparison: typeof import('./src/components/update/VersionComparison.vue')['default']
    VirtualList: typeof import('./src/components/common/VirtualList.vue')['default']
    WidgetConfigDialog: typeof import('./src/components/dashboard/WidgetConfigDialog.vue')['default']
    WidgetWrapper: typeof import('./src/components/dashboard/WidgetWrapper.vue')['default']
  }
}
