# Docker Auto Update System - Production Ready v2.2.0
version: '3.8'

services:
  # Docker Auto Service
  docker-auto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-auto-system
    environment:
      # Application
      - APP_PORT=8080
      - APP_ENV=development
      - LOG_LEVEL=debug
      - LOG_FORMAT=json

      # Database (external or not required)
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=dockerauto
      - DB_USER=dockerauto
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
      - DB_DEBUG=false

      # JWT
      - JWT_SECRET=development-jwt-secret-key-32-chars-minimum-required-for-security
      - JWT_EXPIRE_HOURS=24
      - JWT_REFRESH_DAYS=7

      # Docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=1.41
      - DOCKER_TIMEOUT=30

      # Timezone
      - TZ=Asia/Shanghai
    volumes:
      # Mount Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount logs directory
      - ./logs:/app/logs
    ports:
      - "80:8080"
    networks:
      - docker-auto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  docker-auto-network:
    driver: bridge
    name: docker-auto-network

# No volumes needed for standalone service